stages:
  - build_and_push

build-and-push:
  stage: build_and_push
  variables:
    ARTIFACTORY_REPOSITORY: "ishanarya0"
    IMAGE_NAME: "pg-custom"
    IMAGE_VERSION: "0.1.0"
    POSTGRES_VERSION: "15"
  script:
    - docker build --no-cache -t $ARTIFACTORY_REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION --build-arg POSTGRES_VERSION=${POSTGRES_VERSION} -f Dockerfile .
    - docker push $ARTIFACTORY_REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION
  only:
    - master
  when: manual
